# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdf_converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PDF_Converter(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(759, 520)
        Form.setMinimumSize(QtCore.QSize(759, 520))
        Form.setMaximumSize(QtCore.QSize(759, 520))
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-10, 40, 971, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_status = QtWidgets.QLabel(Form)
        self.label_status.setGeometry(QtCore.QRect(20, 470, 391, 16))
        font = QtGui.QFont()
        font.setFamily("Gotham Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.label_select_file = QtWidgets.QLabel(Form)
        self.label_select_file.setGeometry(QtCore.QRect(20, 100, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Gotham Narrow")
        font.setPointSize(14)
        self.label_select_file.setFont(font)
        self.label_select_file.setObjectName("label_select_file")
        self.pushButton_select = QtWidgets.QPushButton(Form)
        self.pushButton_select.setGeometry(QtCore.QRect(650, 80, 100, 51))
        font = QtGui.QFont()
        font.setFamily("Gotham Narrow")
        font.setPointSize(14)
        self.pushButton_select.setFont(font)
        self.pushButton_select.setObjectName("pushButton_select")
        self.main_label = QtWidgets.QLabel(Form)
        self.main_label.setGeometry(QtCore.QRect(0, 10, 751, 21))
        font = QtGui.QFont()
        font.setFamily("Gotham Narrow")
        font.setPointSize(24)
        self.main_label.setFont(font)
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setObjectName("main_label")
        self.comboBox_source = QtWidgets.QComboBox(Form)
        self.comboBox_source.setGeometry(QtCore.QRect(10, 250, 201, 51))
        self.comboBox_source.setObjectName("comboBox_source")
        self.comboBox_source.addItem("")
        self.comboBox_source.addItem("")
        self.comboBox_source.addItem("")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(-120, 160, 971, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_goingtoconvert = QtWidgets.QLabel(Form)
        self.label_goingtoconvert.setGeometry(QtCore.QRect(20, 230, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Gotham Narrow")
        font.setPointSize(14)
        self.label_goingtoconvert.setFont(font)
        self.label_goingtoconvert.setObjectName("label_goingtoconvert")
        self.comboBox_output = QtWidgets.QComboBox(Form)
        self.comboBox_output.setGeometry(QtCore.QRect(570, 250, 171, 51))
        self.comboBox_output.setObjectName("comboBox_output")
        self.comboBox_output.addItem("")
        self.comboBox_output.addItem("")
        self.comboBox_output.addItem("")
        self.label_tobeconverted = QtWidgets.QLabel(Form)
        self.label_tobeconverted.setGeometry(QtCore.QRect(530, 230, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Gotham Narrow")
        font.setPointSize(14)
        self.label_tobeconverted.setFont(font)
        self.label_tobeconverted.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tobeconverted.setObjectName("label_tobeconverted")
        self.label_select_file_4 = QtWidgets.QLabel(Form)
        self.label_select_file_4.setGeometry(QtCore.QRect(240, 250, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Gotham Narrow")
        font.setPointSize(30)
        self.label_select_file_4.setFont(font)
        self.label_select_file_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_select_file_4.setObjectName("label_select_file_4")
        self.pushButton_convertSave = QtWidgets.QPushButton(Form)
        self.pushButton_convertSave.setGeometry(QtCore.QRect(20, 370, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Gotham Narrow")
        font.setPointSize(14)
        self.pushButton_convertSave.setFont(font)
        self.pushButton_convertSave.setObjectName("pushButton_convertSave")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(520, 390, 231, 111))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PDF Dönüştür"))
        self.label_status.setText(_translate("Form", "Başlamak için bir PDF dosyası seçin..."))
        self.label_select_file.setText(_translate("Form", "Lütfen dosyanızı seçiniz:"))
        self.pushButton_select.setText(_translate("Form", "Dosya Seç"))
        self.main_label.setText(_translate("Form", "PDF Dönüştür"))
        self.comboBox_source.setItemText(0, _translate("Form", "PDF"))
        self.comboBox_source.setItemText(1, _translate("Form", "WORD"))
        self.comboBox_source.setItemText(2, _translate("Form", "JPG"))
        self.label_goingtoconvert.setText(_translate("Form", "Dönüştürülecek dosya formatı"))
        self.comboBox_output.setItemText(0, _translate("Form", "PDF"))
        self.comboBox_output.setItemText(1, _translate("Form", "WORD"))
        self.comboBox_output.setItemText(2, _translate("Form", "JPG"))
        self.label_tobeconverted.setText(_translate("Form", "Dönüşecek dosya formatı"))
        self.label_select_file_4.setText(_translate("Form", "TO"))
        self.pushButton_convertSave.setText(_translate("Form", "Dönüştür ve Kaydet"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Bu bölüm güncelleme almaya devam edecektir. İlginiz için teşekkür ederim.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">mozgor19.</span></p></body></html>"))
